version: "3.5"
services:

  server:
    image: klakegg/hugo:0.54.0
    command: server
    volumes:
      - ".:/src"
    ports:
      - "1313:1313"
    environment:
        HUGO_WATCH: "true"
        HUGO_VERSION: 0.54.0